library(plyr)
tmp <- tempfile()
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip", tmp)
unzip(tmp)
fh <- file("household_power_consumption.txt", "r")
hPower <- read.table(text=grep("^[1,2]/2/2007", readLines(fh), value=TRUE), sep=";", na.strings="?")
unlink(tmp)
colnames(hPower)<- c("Date", "Time", "Global_active_power", "Global_reactive_power", "Voltage", "Global_intensity", "Sub_metering_1", "Sub_metering_2","Sub_metering_3")
DateTime <- paste(hPower$Date, hPower$Time)
hPower$DateTime <- strptime(DateTime, "%d/%m/%Y %H:%M:%S")
png("plot3.png", width=480, height=480, units="px")
with(hPower, {
 plot(DateTime, Sub_metering_1, type="l", ylab="Energy Sub Metering", col = "grey")
  points(hPower$DateTime, hPower$Sub_metering_2, type = "l", col = "red")
  points(hPower$DateTime, hPower$Sub_metering_3, type = "l", col = "blue")
  legend("topright", lty = 1, col = c("grey", "red", "blue"), 
         legend= c("Sub_metering_1", "Sub_metering_2", "Sub_metering_3"))
})
dev.off()
